---
admin: [0.0.0.0, 8020]
inbound-transport:
   - [ws, 0:0:0:0:0:0:0:0, 8021]
   - [http, 0:0:0:0:0:0:0:0, 8022]
outbound-transport: [ws, http]

auto-provision: true
recreate-wallet: false

wallet-type: askar-anoncreds
wallet-storage-type: postgres_storage

auto-ping-connection: true
auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true

auto-store-credential: true

auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-credential-proposal: true

auto-verify-presentation: true
auto-respond-presentation-request: true

preserve-exchange-records: true

plugin:
  - webvh
  # - oid4vc
  - status_list.v1_0
  - connection_update.v1_0
  # - basicmessage_storage.v1_0
  # - multitenant_provider.v1_0

plugin-config-value:
  - did-webvh.server_url=https://id.anoncreds.vc
  - status_list.list_size=200000
  - status_list.shard_size=4
  - status_list.base_url=https://status.test-suite.app